$ErrorActionPreference = "Stop"

function Assert-Exists {
  param([string]$Path)
  if (-not (Test-Path -LiteralPath $Path)) {
    throw "Missing required path: $Path"
  }
}

function Assert-Contains {
  param(
    [string]$Path,
    [string]$Pattern,
    [string]$Message
  )
  $content = Get-Content -LiteralPath $Path -Raw -Encoding UTF8
  if ($content -notmatch $Pattern) {
    throw $Message
  }
}

function Assert-NoUtf8Bom {
  param([string]$Path)
  $bytes = [System.IO.File]::ReadAllBytes($Path)
  if ($bytes.Length -ge 3 -and $bytes[0] -eq 0xEF -and $bytes[1] -eq 0xBB -and $bytes[2] -eq 0xBF) {
    throw "UTF-8 BOM prevents Jekyll from reading front matter: $Path"
  }
}

$requiredPaths = @(
  "_config.yml",
  "_layouts/default.html",
  "_layouts/home.html",
  "_layouts/guide.html",
  "_layouts/category-list.html",
  "_layouts/tag-index.html",
  "_includes/head.html",
  "_includes/footer.html",
  "_includes/giscus.html",
  "_includes/sources.html",
  "_includes/tags.html",
  "_data/tags.yml",
  "_data/sources.yml",
  "guides/loh/2026-05-kyoto-1200/index.html",
  "templates/race-guide.html",
  "race/index.html",
  "training/index.html",
  "support/index.html",
  "factor/index.html",
  "course/index.html",
  "tags/index.html",
  "assets/css/list.css"
)

foreach ($path in $requiredPaths) {
  Assert-Exists $path
}

Get-ChildItem -Recurse -Include *.html,*.md -File |
  Where-Object { $_.FullName -notmatch "\\.git\\" } |
  ForEach-Object { Assert-NoUtf8Bom $_.FullName }

Assert-Contains "_config.yml" "permalink:\s+/guides/race/:path/" "_config.yml must output race guides under /guides/race/:path/"
Assert-Contains "_config.yml" "future:\s+true" "_config.yml must include future-dated guide documents in collection lists"
Assert-Contains "_layouts/guide.html" "include\s+giscus.html" "guide layout must include giscus"
Assert-Contains "_layouts/guide.html" "article:published_time" "guide layout must output article published time"
Assert-Contains "_includes/giscus.html" 'data-mapping="pathname"' "giscus must map discussions by pathname"
Assert-Contains "_includes/sources.html" "page\.sources" "sources include must be driven by page.sources"
Assert-Contains "index.html" "site\.pages" "home page must read public guide pages under guides/"
Assert-Contains "index.html" "/guides/loh/2026-05-kyoto-1200/" "home page must keep a fallback link to the existing LoH guide"
Assert-Contains "_layouts/tag-index.html" "site\.pages" "tag index must read public guide pages under guides/"
Assert-Contains "_layouts/category-list.html" "site\.pages" "category lists must read public guide pages under guides/"
Assert-Contains "_layouts/category-list.html" "/guides/loh/2026-05-kyoto-1200/" "race category list must keep a fallback link to the existing LoH guide"
Assert-Contains "guides/loh/2026-05-kyoto-1200/index.html" "sources:" "LoH guide page must declare sources front matter"
Assert-Contains "guides/loh/2026-05-kyoto-1200/index.html" "permalink:\s+/guides/loh/2026-05-kyoto-1200/" "May 2026 LoH guide must use its public URL"
Assert-Contains "guides/loh/2026-05-kyoto-1200/index.html" "layout:\s+guide" "LoH guide page must explicitly use the guide layout"
Assert-Contains "guides/loh/2026-05-kyoto-1200/index.html" "css:\s+guide" "LoH guide page must explicitly load guide.css"
Assert-Contains "guides/loh/2026-05-kyoto-1200/index.html" "category:\s+race" "LoH guide page must declare category for category list output"
Assert-Contains "AGENTS.md" "Jekyll Collection" "AGENTS.md must document Jekyll collection operations"
Assert-Contains "README.md" "_race/" "README.md must summarize the Jekyll collection structure"
Assert-Contains ".gitignore" "_site/" ".gitignore must ignore Jekyll output"
Assert-Contains ".gitignore" "\.jekyll-cache/" ".gitignore must ignore Jekyll cache"

if (Test-Path -LiteralPath "sitemap.xml") {
  throw "sitemap.xml should be generated by jekyll-sitemap, not kept as a static file"
}

Write-Output "Jekyll structure validation passed."
