$ErrorActionPreference = "Stop"

function Assert-Exists {
  param([string]$Path)
  if (-not (Test-Path -LiteralPath $Path)) {
    throw "Missing required path: $Path"
  }
}

function Assert-Contains {
  param(
    [string]$Path,
    [string]$Pattern,
    [string]$Message
  )
  $content = Get-Content -LiteralPath $Path -Raw -Encoding UTF8
  if ($content -notmatch $Pattern) {
    throw $Message
  }
}

$requiredPaths = @(
  "_config.yml",
  "_layouts/default.html",
  "_layouts/home.html",
  "_layouts/guide.html",
  "_layouts/category-list.html",
  "_layouts/tag-index.html",
  "_includes/head.html",
  "_includes/footer.html",
  "_includes/giscus.html",
  "_includes/sources.html",
  "_includes/tags.html",
  "_data/tags.yml",
  "_data/sources.yml",
  "_race/2026-05-kyoto-1200.html",
  "templates/race-guide.html",
  "race/index.html",
  "training/index.html",
  "support/index.html",
  "factor/index.html",
  "course/index.html",
  "tags/index.html",
  "assets/css/list.css"
)

foreach ($path in $requiredPaths) {
  Assert-Exists $path
}

Assert-Contains "_config.yml" "permalink:\s+/guides/race/:path/" "_config.yml must output race guides under /guides/race/:path/"
Assert-Contains "_layouts/guide.html" "include\s+giscus.html" "guide layout must include giscus"
Assert-Contains "_layouts/guide.html" "article:published_time" "guide layout must output article published time"
Assert-Contains "_includes/giscus.html" 'data-mapping="pathname"' "giscus must map discussions by pathname"
Assert-Contains "_includes/sources.html" "page\.sources" "sources include must be driven by page.sources"
Assert-Contains "index.html" "site\.race" "home page must read collection articles"
Assert-Contains "_race/2026-05-kyoto-1200.html" "sources:" "migrated race guide must declare sources front matter"
Assert-Contains "AGENTS.md" "Jekyll Collection" "AGENTS.md must document Jekyll collection operations"
Assert-Contains "README.md" "_race/" "README.md must summarize the Jekyll collection structure"
Assert-Contains ".gitignore" "_site/" ".gitignore must ignore Jekyll output"
Assert-Contains ".gitignore" "\.jekyll-cache/" ".gitignore must ignore Jekyll cache"

if (Test-Path -LiteralPath "sitemap.xml") {
  throw "sitemap.xml should be generated by jekyll-sitemap, not kept as a static file"
}

Write-Output "Jekyll structure validation passed."
